import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'fi' | 'sv';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.workflows": "Workflows",
    "nav.case_studies": "Case Studies",
    "nav.services": "Services",
    "nav.inquire": "Inquire",
    "nav.services.automation": "AI Automation",
    "nav.services.workflow": "Workflow Automation",
    "nav.services.custom": "Custom Software",
    "hero.subtitle": "Built for real operational workflows.",
    "hero.title1": "Less manual work.",
    "hero.title2": "Better",
    "hero.title2_accent": "operations.",
    "hero.desc": "We help organizations identify repetitive work that can be automated securely with AI.",
    "hero.cta_primary": "Book a 30-min call",
    "hero.cta_secondary": "The Proof of ROI",
    "home.philosophy.title": "What we build",
    "home.philosophy.desc": "Invoice processing that runs itself. Lead scoring that updates nightly. Internal search that actually finds things. We build specific tools for specific problems.",
    "home.stat.opex": "OPEX Reduction",
    "home.stat.hours": "Manual Hours Saved",
    "home.clients.title": "Worked for",
    "home.ready": "Ready to automate your bottlenecks?",
    "home.ready_desc": "Book a 30-min call. We'll review your workflows and tell you honestly whether automation would help (and if not, we'll say so).",
    "home.begin": "Book a call",
    "footer.tagline": "Based in Helsinki, Finland. Small team. 3-4 projects at a time. We'd rather do great work than lots of work.",
    "footer.services": "Services",
    "footer.company": "Company",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "workflows.title": "Workflow Library",
    "workflows.desc": "A collection of high-impact automations we have deployed. Real problems, engineered solutions, measurable ROI.",
    "workflows.filter": "Filter",
    "workflows.all_ind": "All Industries",
    "workflows.all_dept": "All Departments",
    "workflows.search": "Search workflows...",
    "workflows.pain": "The Pain",
    "workflows.solution": "The Solution",
    "workflows.discuss": "Discuss Implementation",
    "workflows.empty": "No workflows found matching your criteria.",
    "workflows.clear": "Clear filters",
    "cases.title": "Case Studies",
    "cases.desc": "Proof of impact. How we helped minimal-infrastructure startups become efficient enterprises.",
    "cases.problem": "The Problem:",
    "cases.old": "The Old Way:",
    "cases.sol": "The Solution:",
    "cases.outcome": "Outcome:",
    "cases.viz": "Case Study Visualization",
    "cases.cta": "Ready to be our next case study?",
    "cases.btn": "Let's Talk ROI",
    "contact.title": "Inquire",
    "contact.desc": "Describe your biggest bottleneck. We'll tell you if automation can fix it, what it costs, and how long.",
    "contact.email": "Email",
    "contact.hq": "Address",
    "contact.assurance": "Assurance",
    "contact.assurance_desc": "We respect the quiet. No spam lists, no aggressive sales follow-ups. Just engineering discussions.",
    "contact.form.name": "Name",
    "contact.form.role": "Role",
    "contact.form.email": "Work Email",
    "contact.form.interest": "Area of Interest",
    "contact.form.select": "Select a topic...",
    "contact.form.details": "Project Details",
    "contact.form.submit": "Request Session",
    "contact.success.title": "Message Received.",
    "contact.success.desc": "Thanks! I'll personally read your message and get back within 24hrs — usually sooner.",
    "contact.success.steps": "Next Steps",
    "contact.success.step1": "1. We review your current infrastructure needs.",
    "contact.success.step2": "2. We prepare an initial automation roadmap.",
    "contact.success.step3": "3. We schedule a 30-min discovery call.",
    "contact.back": "Back to Site",
    "booking.sticky": "Book Discovery Call"
  },
  fi: {
    "nav.workflows": "Työnkulut",
    "nav.case_studies": "Asiakastarinat",
    "nav.services": "Palvelut",
    "nav.inquire": "Ota yhteyttä",
    "nav.services.automation": "Tekoälyautomaatio",
    "nav.services.workflow": "Työnkulkujen automaatio",
    "nav.services.custom": "Räätälöity ohjelmistokehitys",
    "hero.subtitle": "Tekoälyautomaatio keskisuurille yrityksille.",
    "hero.title1": "Rakennamme järjestelmiä, jotka hoitavat",
    "hero.title2": "toistuvan työn",
    "hero.title2_accent": "automaattisesti.",
    "hero.desc": "Suunnittelemme ja otamme käyttöön tekoälyautomaatiota keskisuurille yrityksille, jotka hukkuvat manuaalisiin työnkulkuihin. Ei muotisanoja. Ei kojelautoja, joita et koskaan tarkista. Vain järjestelmiä, jotka hoitavat työn hiljaa.",
    "hero.cta_primary": "Varaa ilmainen 30 min puhelu",
    "hero.cta_secondary": "Todisteet ROI:sta",
    "home.philosophy.title": "Mitä rakennamme",
    "home.philosophy.desc": "Laskujen käsittely, joka toimii itsestään. Liidien pisteytys, joka päivittyy öisin. Sisäinen haku, joka todella löytää asioita. Rakennamme erityisiä työkaluja erityisiin ongelmiin.",
    "home.stat.opex": "OPEX-vähennys",
    "home.stat.hours": "Säästetyt manuaaliset tunnit",
    "home.clients.title": "Työskennellyt",
    "home.ready": "Valmis automatisoimaan pullonkaulasi?",
    "home.ready_desc": "Varaa ilmainen 30 min puhelu. Käymme läpi työnkulkusi ja kerromme rehellisesti, auttaisiko automaatio (ja jos ei, sanomme sen).",
    "home.begin": "Varaa puhelu",
    "footer.tagline": "Sijaitsee Helsingissä, Suomessa. Pieni tiimi. 3-4 projektia kerrallaan. Haluamme tehdä hienoa työtä, emme paljon työtä.",
    "footer.services": "Palvelut",
    "footer.company": "Yritys",
    "footer.privacy": "Tietosuoja",
    "footer.terms": "Ehdot",
    "workflows.title": "Työnkulkukirjasto",
    "workflows.desc": "Kokoelma käyttöönotettuja, vaikuttavia automaatioita. Todellisia ongelmia, suunniteltuja ratkaisuja, mitattavaa sijoitetun pääoman tuottoa.",
    "workflows.filter": "Suodata",
    "workflows.all_ind": "Kaikki toimialat",
    "workflows.all_dept": "Kaikki osastot",
    "workflows.search": "Etsi työnkulkuja...",
    "workflows.pain": "Ongelma",
    "workflows.solution": "Ratkaisu",
    "workflows.discuss": "Keskustele toteutuksesta",
    "workflows.empty": "Kriteereitäsi vastaavia työnkulkuja ei löytynyt.",
    "workflows.clear": "Tyhjennä suodattimet",
    "cases.title": "Asiakastarinat",
    "cases.desc": "Todiste vaikutuksesta. Kuinka autoimme minimaalisen infrastruktuurin startup-yrityksiä tulemaan tehokkaiksi yrityksiksi.",
    "cases.problem": "Ongelma:",
    "cases.old": "Vanha tapa:",
    "cases.sol": "Ratkaisu:",
    "cases.outcome": "Tulos:",
    "cases.viz": "Tapaustutkimuksen visualisointi",
    "cases.cta": "Haluatko olla seuraava menestystarinamme?",
    "cases.btn": "Puhutaan ROI:sta",
    "contact.title": "Tiedustele",
    "contact.desc": "Kuvaile suurin pullonkaulasi. Kerromme, voiko automaatio korjata sen, mitä se maksaa ja kuinka kauan kestää.",
    "contact.email": "Sähköposti",
    "contact.hq": "Osoite",
    "contact.assurance": "Vakuutus",
    "contact.assurance_desc": "Kunnioitamme hiljaisuutta. Ei roskapostilistoja, ei aggressiivista myynnin seurantaa. Vain teknisiä keskusteluja.",
    "contact.form.name": "Nimi",
    "contact.form.role": "Rooli",
    "contact.form.email": "Työsähköposti",
    "contact.form.interest": "Kiinnostuksen kohde",
    "contact.form.select": "Valitse aihe...",
    "contact.form.details": "Projektin tiedot",
    "contact.form.submit": "Pyydä istuntoa",
    "contact.success.title": "Viesti vastaanotettu.",
    "contact.success.desc": "Kiitos! Luen viestisi henkilökohtaisesti ja vastaan 24 tunnin kuluessa — yleensä nopeammin.",
    "contact.success.steps": "Seuraavat vaiheet",
    "contact.success.step1": "1. Tarkistamme nykyiset infrastruktuuritarpeesi.",
    "contact.success.step2": "2. Valmistelemme alustavan automaation tiekartan.",
    "contact.success.step3": "3. Aikataulutamme 30 minuutin kartoituspuhelun.",
    "contact.back": "Takaisin sivustolle",
    "booking.sticky": "Varaa kartoituspuhelu"
  },
  sv: {
    "nav.workflows": "Arbetsflöden",
    "nav.case_studies": "Fallstudier",
    "nav.services": "Tjänster",
    "nav.inquire": "Fråga oss",
    "nav.services.automation": "AI-automatisering",
    "nav.services.workflow": "Arbetsflödesautomatisering",
    "nav.services.custom": "Anpassad mjukvara",
    "hero.subtitle": "AI-automatisering för medelstora företag.",
    "hero.title1": "Vi bygger system som hanterar",
    "hero.title2": "repetitivt arbete",
    "hero.title2_accent": "automatiskt.",
    "hero.desc": "Vi designar och implementerar AI-automatisering för medelstora företag som drunknar i manuella arbetsflöden. Inga buzzwords. Inga dashboards du aldrig kollar. Bara system som tyst hanterar arbetet.",
    "hero.cta_primary": "Boka ett gratis 30-min samtal",
    "hero.cta_secondary": "Bevis på ROI",
    "home.philosophy.title": "Vad vi bygger",
    "home.philosophy.desc": "Fakturabehandling som kör sig själv. Leadpoäng som uppdateras nattetid. Intern sökning som faktiskt hittar saker. Vi bygger specifika verktyg för specifika problem.",
    "home.stat.opex": "OPEX-minskning",
    "home.stat.hours": "Sparade manuella timmar",
    "home.clients.title": "Arbetat för",
    "home.ready": "Redo att automatisera dina flaskhalsar?",
    "home.ready_desc": "Boka ett gratis 30-min samtal. Vi går igenom dina arbetsflöden och berättar ärligt om automatisering skulle hjälpa (och om inte, säger vi det).",
    "home.begin": "Boka ett samtal",
    "footer.tagline": "Baserat i Helsingfors, Finland. Litet team. 3-4 projekt åt gången. Vi gör hellre bra arbete än mycket arbete.",
    "footer.services": "Tjänster",
    "footer.company": "Företag",
    "footer.privacy": "Integritet",
    "footer.terms": "Villkor",
    "workflows.title": "Arbetsflödesbibliotek",
    "workflows.desc": "En samling av effektiva automatiseringar vi har implementerat. Verkliga problem, konstruerade lösningar, mätbar ROI.",
    "workflows.filter": "Filtrera",
    "workflows.all_ind": "Alla branscher",
    "workflows.all_dept": "Alla avdelningar",
    "workflows.search": "Sök arbetsflöden...",
    "workflows.pain": "Smärtan",
    "workflows.solution": "Lösningen",
    "workflows.discuss": "Diskutera implementering",
    "workflows.empty": "Inga arbetsflöden hittades som matchar dina kriterier.",
    "workflows.clear": "Rensa filter",
    "cases.title": "Fallstudier",
    "cases.desc": "Bevis på effekt. Hur vi hjälpte startups med minimal infrastruktur att bli effektiva företag.",
    "cases.problem": "Problemet:",
    "cases.old": "Det gamla sättet:",
    "cases.sol": "Lösningen:",
    "cases.outcome": "Resultat:",
    "cases.viz": "Visualisering av fallstudie",
    "cases.cta": "Redo att bli vår nästa framgångssaga?",
    "cases.btn": "Låt oss prata ROI",
    "contact.title": "Fråga oss",
    "contact.desc": "Beskriv din största flaskhals. Vi berättar om automatisering kan fixa det, vad det kostar och hur lång tid.",
    "contact.email": "E-post",
    "contact.hq": "Adress",
    "contact.assurance": "Försäkran",
    "contact.assurance_desc": "Vi respekterar tystnaden. Inga spamlistor, inga aggressiva säljuppföljningar. Bara tekniska diskussioner.",
    "contact.form.name": "Namn",
    "contact.form.role": "Roll",
    "contact.form.email": "Arbets-e-post",
    "contact.form.interest": "Intresseområde",
    "contact.form.select": "Välj ett ämne...",
    "contact.form.details": "Projektdetaljer",
    "contact.form.submit": "Begär session",
    "contact.success.title": "Meddelande mottaget.",
    "contact.success.desc": "Tack! Jag läser ditt meddelande personligen och svarar inom 24 timmar — oftast snabbare.",
    "contact.success.steps": "Nästa steg",
    "contact.success.step1": "1. Vi ser över dina nuvarande infrastrukturbehov.",
    "contact.success.step2": "2. Vi förbereder en preliminär automatiseringsplan.",
    "contact.success.step3": "3. Vi bokar ett 30 minuters upptäcktsamtal.",
    "contact.back": "Tillbaka till webbplatsen",
    "booking.sticky": "Boka upptäcktsamtal"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};