import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'fi' | 'sv';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.workflows": "Workflows",
    "nav.case_studies": "Case Studies",
    "nav.services": "Services",
    "nav.inquire": "Inquire",
    "nav.services.enablement": "AI Enablement",
    "nav.services.automation": "AI Automation",
    "nav.services.workflow": "Workflow Automation",
    "nav.services.custom": "Custom Software",
    "nav.geo": "GEO",
    "hero.subtitle": "Low-friction intelligence.",
    "hero.title1": "Scaled without the noise.",
    "hero.title2": "Built with",
    "hero.title2_accent": "quiet confidence.",
    "hero.desc": "BrewMy{Code} engineers silent AI systems for leadership that values measurable outcomes over hype. We automate the mundane so you can govern the exceptional.",
    "hero.cta_primary": "Request Strategy Session",
    "hero.cta_secondary": "The Proof of ROI",
    "home.philosophy.title": "The Philosophy of Silence",
    "home.philosophy.desc": "We believe the best technology is that which isn't felt. No flashy UI gimmicks. No aggressive notifications. Just pure utility running in the background of your business.",
    "home.stat.opex": "OPEX Reduction",
    "home.stat.hours": "Manual Hours Saved",
    "home.ready": "Ready to silence the noise?",
    "home.ready_desc": "Schedule a consultation with our systems architects. No sales pressure, just engineering possibilities.",
    "home.begin": "Begin the Conversation",
    "footer.tagline": "Engineering silent intelligence for leadership that values outcomes over noise.",
    "footer.services": "Services",
    "footer.company": "Company",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "workflows.title": "Workflow Library",
    "workflows.desc": "A collection of high-impact automations we have deployed. Real problems, engineered solutions, measurable ROI.",
    "workflows.filter": "Filter",
    "workflows.all_ind": "All Industries",
    "workflows.all_dept": "All Departments",
    "workflows.search": "Search workflows...",
    "workflows.pain": "The Pain",
    "workflows.solution": "The Solution",
    "workflows.discuss": "Discuss Implementation",
    "workflows.empty": "No workflows found matching your criteria.",
    "workflows.clear": "Clear filters",
    "cases.title": "Case Studies",
    "cases.desc": "Proof of impact. How we helped minimal-infrastructure startups become efficient enterprises.",
    "cases.problem": "The Problem:",
    "cases.old": "The Old Way:",
    "cases.sol": "The Solution:",
    "cases.outcome": "Outcome:",
    "cases.viz": "Case Study Visualization",
    "cases.cta": "Ready to be our next case study?",
    "cases.btn": "Let's Talk ROI",
    "contact.title": "Inquire",
    "contact.desc": "Tell us about the friction in your business. We'll design the lubricant.",
    "contact.email": "Email",
    "contact.hq": "Address",
    "contact.assurance": "Assurance",
    "contact.assurance_desc": "We respect the quiet. No spam lists, no aggressive sales follow-ups. Just engineering discussions.",
    "contact.form.name": "Name",
    "contact.form.role": "Role",
    "contact.form.email": "Work Email",
    "contact.form.interest": "Area of Interest",
    "contact.form.select": "Select a topic...",
    "contact.form.details": "Project Details",
    "contact.form.submit": "Request Session",
    "contact.success.title": "Message Received.",
    "contact.success.desc": "Thank you. Our strategy team is reviewing your profile. Expect a personal response within 24 hours.",
    "contact.success.steps": "Next Steps",
    "contact.success.step1": "1. We review your current infrastructure needs.",
    "contact.success.step2": "2. Vi valmistelemme alustavan automaation tiekartan.",
    "contact.success.step3": "3. We schedule a 30-min discovery call.",
    "contact.back": "Back to Site",
    "booking.sticky": "Book Discovery Call"
  },
  fi: {
    "nav.workflows": "Työnkulut",
    "nav.case_studies": "Asiakastarinat",
    "nav.services": "Palvelut",
    "nav.inquire": "Ota yhteyttä",
    "nav.services.enablement": "Tekoälyn käyttöönotto",
    "nav.services.automation": "Tekoälyautomaatio",
    "nav.services.workflow": "Työnkulkujen automaatio",
    "nav.services.custom": "Räätälöity ohjelmistokehitys",
    "nav.geo": "GEO",
    "hero.subtitle": "Vähäkitkaista älykkyyttä.",
    "hero.title1": "Skaalautuu ilman melua.",
    "hero.title2": "Rakennettu",
    "hero.title2_accent": "hiljaisella varmuudella.",
    "hero.desc": "BrewMy{Code} suunnittelee hiljaisia tekoälyjärjestelmiä johtajille, jotka arvostavat mitattavia tuloksia hypetyksen sijaan. Automatisoimme arkipäiväiset tehtävät, jotta voit hallita poikkeuksia.",
    "hero.cta_primary": "Varaa strategiapuhelu",
    "hero.cta_secondary": "Todisteet ROI:sta",
    "home.philosophy.title": "Hiljaisuuden filosofia",
    "home.philosophy.desc": "Uskomme, että paras teknologia on sellaista, jota ei huomaa. Ei räikeitä käyttöliittymäkikkoja. Ei aggressiivisia ilmoituksia. Vain puhdasta hyötyä liiketoimintasi taustalla.",
    "home.stat.opex": "OPEX-vähennys",
    "home.stat.hours": "Säästetyt manuaaliset tunnit",
    "home.ready": "Valmis hiljentämään melun?",
    "home.ready_desc": "Varaa konsultointi järjestelmäarkkitehdeiltamme. Ei myyntipainetta, vain teknisiä mahdollisuuksia.",
    "home.begin": "Aloita keskustelu",
    "footer.tagline": "Suunnittelemme hiljaista älykkyyttä johtajille, jotka arvostavat tuloksia melun sijaan.",
    "footer.services": "Palvelut",
    "footer.company": "Yritys",
    "footer.privacy": "Tietosuoja",
    "footer.terms": "Ehdot",
    "workflows.title": "Työnkulkukirjasto",
    "workflows.desc": "Kokoelma käyttöönotettuja, vaikuttavia automaatioita. Todellisia ongelmia, suunniteltuja ratkaisuja, mitattavaa sijoitetun pääoman tuottoa.",
    "workflows.filter": "Suodata",
    "workflows.all_ind": "Kaikki toimialat",
    "workflows.all_dept": "Kaikki osastot",
    "workflows.search": "Etsi työnkulkuja...",
    "workflows.pain": "Ongelma",
    "workflows.solution": "Ratkaisu",
    "workflows.discuss": "Keskustele toteutuksesta",
    "workflows.empty": "Kriteereitäsi vastaavia työnkulkuja ei löytynyt.",
    "workflows.clear": "Tyhjennä suodattimet",
    "cases.title": "Asiakastarinat",
    "cases.desc": "Todiste vaikutuksesta. Kuinka autoimme minimaalisen infrastruktuurin startup-yrityksiä tulemaan tehokkaiksi yrityksiksi.",
    "cases.problem": "Ongelma:",
    "cases.old": "Vanha tapa:",
    "cases.sol": "Ratkaisu:",
    "cases.outcome": "Tulos:",
    "cases.viz": "Tapaustutkimuksen visualisointi",
    "cases.cta": "Haluatko olla seuraava menestystarinamme?",
    "cases.btn": "Puhutaan ROI:sta",
    "contact.title": "Tiedustele",
    "contact.desc": "Kerro meille liiketoimintasi kitkasta. Me suunnittelemme voiteluaineen.",
    "contact.email": "Sähköposti",
    "contact.hq": "Osoite",
    "contact.assurance": "Vakuutus",
    "contact.assurance_desc": "Kunnioitamme hiljaisuutta. Ei roskapostilistoja, ei aggressiivista myynnin seurantaa. Vain teknisiä keskusteluja.",
    "contact.form.name": "Nimi",
    "contact.form.role": "Rooli",
    "contact.form.email": "Työsähköposti",
    "contact.form.interest": "Kiinnostuksen kohde",
    "contact.form.select": "Valitse aihe...",
    "contact.form.details": "Projektin tiedot",
    "contact.form.submit": "Pyydä istuntoa",
    "contact.success.title": "Viesti vastaanotettu.",
    "contact.success.desc": "Kiitos. Strategiatiimimme tarkastelee profiiliasi. Odotettavissa henkilökohtainen vastaus 24 tunnin kuluessa.",
    "contact.success.steps": "Seuraavat vaiheet",
    "contact.success.step1": "1. Tarkistamme nykyiset infrastruktuuritarpeesi.",
    "contact.success.step2": "2. Valmistelemme alustavan automaation tiekartan.",
    "contact.success.step3": "3. Aikataulutamme 30 minuutin kartoituspuhelun.",
    "contact.back": "Takaisin sivustolle",
    "booking.sticky": "Varaa kartoituspuhelu"
  },
  sv: {
    "nav.workflows": "Arbetsflöden",
    "nav.case_studies": "Fallstudier",
    "nav.services": "Tjänster",
    "nav.inquire": "Fråga oss",
    "nav.services.enablement": "AI-aktivering",
    "nav.services.automation": "AI-automatisering",
    "nav.services.workflow": "Arbetsflödesautomatisering",
    "nav.services.custom": "Anpassad mjukvara",
    "nav.geo": "GEO",
    "hero.subtitle": "Intelligens med låg friktion.",
    "hero.title1": "Skalad utan bruset.",
    "hero.title2": "Byggd med",
    "hero.title2_accent": "tyst självförtroende.",
    "hero.desc": "BrewMy{Code} konstruerar tysta AI-system för ledarskap som värdesätter mätbara resultat över hype. Vi automatiserar det vardagliga så att du kan styra det exceptionella.",
    "hero.cta_primary": "Begär strategisession",
    "hero.cta_secondary": "Bevis på ROI",
    "home.philosophy.title": "Tystnadens filosofi",
    "home.philosophy.desc": "Vi tror att den bästa tekniken är den som inte känns. Inga flashiga UI-jippon. Inga aggressiva aviseringar. Bara ren nytta som körs i bakgrunden av ditt företag.",
    "home.stat.opex": "OPEX-minskning",
    "home.stat.hours": "Sparade manuella timmar",
    "home.ready": "Redo att tysta bruset?",
    "home.ready_desc": "Boka en konsultation med våra systemarkitekter. Inget säljtjat, bara tekniska möjligheter.",
    "home.begin": "Börja samtalet",
    "footer.tagline": "Konstruerar tyst intelligens för ledarskap som värdesätter resultat över brus.",
    "footer.services": "Tjänster",
    "footer.company": "Företag",
    "footer.privacy": "Integritet",
    "footer.terms": "Villkor",
    "workflows.title": "Arbetsflödesbibliotek",
    "workflows.desc": "En samling av effektiva automatiseringar vi har implementerat. Verkliga problem, konstruerade lösningar, mätbar ROI.",
    "workflows.filter": "Filtrera",
    "workflows.all_ind": "Alla branscher",
    "workflows.all_dept": "Alla avdelningar",
    "workflows.search": "Sök arbetsflöden...",
    "workflows.pain": "Smärtan",
    "workflows.solution": "Lösningen",
    "workflows.discuss": "Diskutera implementering",
    "workflows.empty": "Inga arbetsflöden hittades som matchar dina kriterier.",
    "workflows.clear": "Rensa filter",
    "cases.title": "Fallstudier",
    "cases.desc": "Bevis på effekt. Hur vi hjälpte startups med minimal infrastruktur att bli effektiva företag.",
    "cases.problem": "Problemet:",
    "cases.old": "Det gamla sättet:",
    "cases.sol": "Lösningen:",
    "cases.outcome": "Resultat:",
    "cases.viz": "Visualisering av fallstudie",
    "cases.cta": "Redo att bli vår nästa framgångssaga?",
    "cases.btn": "Låt oss prata ROI",
    "contact.title": "Fråga oss",
    "contact.desc": "Berätta om friktionen i ditt företag. Vi designar smörjmedlet.",
    "contact.email": "E-post",
    "contact.hq": "Adress",
    "contact.assurance": "Försäkran",
    "contact.assurance_desc": "Vi respekterar tystnaden. Inga spamlistor, inga aggressiva säljuppföljningar. Bara tekniska diskussioner.",
    "contact.form.name": "Namn",
    "contact.form.role": "Roll",
    "contact.form.email": "Arbets-e-post",
    "contact.form.interest": "Intresseområde",
    "contact.form.select": "Välj ett ämne...",
    "contact.form.details": "Projektdetaljer",
    "contact.form.submit": "Begär session",
    "contact.success.title": "Meddelande mottaget.",
    "contact.success.desc": "Tack. Vårt strategiteam granskar din profil. Förvänta dig ett personligt svar inom 24 timmar.",
    "contact.success.steps": "Nästa steg",
    "contact.success.step1": "1. Vi ser över dina nuvarande infrastrukturbehov.",
    "contact.success.step2": "2. Vi förbereder en preliminär automatiseringsplan.",
    "contact.success.step3": "3. Vi bokar ett 30 minuters upptäcktsamtal.",
    "contact.back": "Tillbaka till webbplatsen",
    "booking.sticky": "Boka upptäcktsamtal"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};